### PR TITLE
fix #532: Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier, and twemoji.parse return type

### LINKED ISSUE #532: Type error in v14.0
**Describe the bug**
```bash
../../node_modules/.pnpm/twemoji@14.0.0/node_modules/twemoji/index.d.ts:32:1 - error TS1046: Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.

32 const twemoji: {
```

**To Reproduce**
1. Go to https://github.com/Saul-Mirone/milkdown
2. `git checkout renovate/all`
3. `pnpm install && pnpm build --filter=@milkdown/plugin-emoji`

**Expected behavior**
Typescript compile can pass with no error.

**Screenshots**
image

**Environment**
For web, specify your OS and browser version.  For mobile, specify device, OS
and version.  For libraries, what version of build tools are you using?

**Additional context**

### PR DESCRIPTION
**Pull request by hthetiot**
- Fix Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier reported on #532
- Fix Twemoji.parse return type to string instead of void

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -29,13 +29,15 @@ interface TwemojiOptions {
   attributes?(): void;
 }
 
-const twemoji: {
+declare type twemoji = {
```
Comment (hthetiot) [inline index.d.ts:32]: May be "Twemoji" cause it's a type.

**Review by jdecked — APPROVED** [review]

**Comment by evanjo03** [comment]
I'm seeing the same exact error using v13... does this fix need to be applied as a patch for that major version as well?
